import { createContext, useContext, useEffect, useState } from 'react'
import { Link, Navigate, NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { Activity, AlertTriangle, Bell, Check, ChevronDown, Cloud, Cpu, Database, HardDrive, LayoutDashboard, LockKeyhole, LogOut, Menu, Moon, Network, Search, Server, Settings, ShieldCheck, Sun, UserPlus, Users, X, Zap } from 'lucide-react'
import { mockApi } from './mockApi'

const TOKEN_KEY = 'noc-automation-token'
const USER_KEY = 'noc-automation-user'
const API_BASE = import.meta.env.VITE_API_URL || '/api'
const AuthContext = createContext(null)

async function apiRequest(path, options = {}) {
  const response = await fetch(`${API_BASE}${path}`, {
    ...options,
    headers: { 'Content-Type': 'application/json', ...(options.token ? { Authorization: `Bearer ${options.token}` } : {}), ...(options.headers || {}) },
  })
  const data = response.status === 204 ? null : await response.json()
  if (!response.ok) throw new Error(data?.error || 'Request failed.')
  return data
}

function AuthProvider({ children }) {
  const [token, setToken] = useState(() => localStorage.getItem(TOKEN_KEY))
  const [user, setUser] = useState(() => { try { return JSON.parse(localStorage.getItem(USER_KEY)) || null } catch { return null } })
  const [ready, setReady] = useState(() => !localStorage.getItem(TOKEN_KEY))
  useEffect(() => {
    if (!token) { setReady(true); return undefined }
    let cancelled = false
    setReady(false)
    apiRequest('/auth/me', { token }).then(({ user: nextUser }) => {
      if (!cancelled) { setUser(nextUser); localStorage.setItem(USER_KEY, JSON.stringify(nextUser)) }
    }).catch(() => {
      if (!cancelled) { localStorage.removeItem(TOKEN_KEY); localStorage.removeItem(USER_KEY); setToken(null); setUser(null) }
    }).finally(() => { if (!cancelled) setReady(true) })
    return () => { cancelled = true }
  }, [token])
  const signIn = async (email, password) => { const data = await apiRequest('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); localStorage.setItem(TOKEN_KEY, data.token); localStorage.setItem(USER_KEY, JSON.stringify(data.user)); setUser(data.user); setToken(data.token); return data }
  const register = async (name, email, password, role) => { const data = await apiRequest('/auth/register', { method: 'POST', body: JSON.stringify({ name, email, password, role }) }); localStorage.setItem(TOKEN_KEY, data.token); localStorage.setItem(USER_KEY, JSON.stringify(data.user)); setUser(data.user); setToken(data.token); return data }
  const signOut = async () => { try { if (token) await apiRequest('/auth/logout', { method: 'POST', token }) } finally { localStorage.removeItem(TOKEN_KEY); localStorage.removeItem(USER_KEY); setUser(null); setToken(null) } }
  return <AuthContext.Provider value={{ user, ready, authenticated: Boolean(token && user), signIn, register, signOut }}>{children}</AuthContext.Provider>
}
function useAuth() { return useContext(AuthContext) }

function App() {
  return <AuthProvider><Routes>
    <Route path="/login" element={<Login />} /><Route path="/register" element={<Register />} /><Route path="/forgot-password" element={<ForgotPassword />} />
    <Route element={<ProtectedRoute />}><Route path="/dashboard" element={<Dashboard />} /><Route path="/monitoring" element={<MonitoringPage />} /><Route path="/alerts" element={<AlertsPage />} /><Route path="/reports" element={<ReportsPage />} /><Route path="/settings" element={<SettingsPage />} /></Route>
    <Route path="*" element={<Navigate to="/dashboard" replace />} />
  </Routes></AuthProvider>
}
function ProtectedRoute() { const { authenticated, ready } = useAuth(); return !ready ? null : authenticated ? <AppShell /> : <Navigate to="/login" replace /> }

function AuthLayout({ eyebrow, title, text, children }) {
  return <main className="auth-page"><div className="auth-visual"><div className="visual-grid" /><div className="auth-orbit orbit-one" /><div className="auth-orbit orbit-two" /><div className="auth-signal"><Activity size={22} /><span>NOC / SECURE</span></div><div className="auth-visual-copy"><span className="status-dot" />Always-on infrastructure operations.</div></div><section className="auth-panel"><Link to="/login" className="brand"><span className="brand-mark"><span /></span><span>NOC <span className="brand-accent">Automation</span></span></Link><div className="auth-copy"><span className="auth-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{children}<div className="auth-footer"><span>NOC Automation Operations Center</span><span>v2.4.0</span></div></section></main>
}
function Login() {
  const { signIn } = useAuth(); const navigate = useNavigate(); const [email, setEmail] = useState('admin@nocautomation.com'); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [pending, setPending] = useState(false)
  const submit = async event => { event.preventDefault(); setError(''); setPending(true); try { await signIn(email, password); navigate('/dashboard') } catch (requestError) { setError(requestError.message) } finally { setPending(false) } }
  return <AuthLayout eyebrow="Welcome back" title={<>Your network.<br /><span>Always ready.</span></>} text="Sign in to monitor infrastructure, investigate incidents, and keep critical services available."><form className="auth-form" onSubmit={submit}><Field label="Work email" type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="you@company.com" required /><Field label="Password" type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="Enter your password" required /><div className="form-row"><label className="checkbox"><input type="checkbox" defaultChecked /> Remember me</label><Link to="/forgot-password">Forgot password?</Link></div>{error && <p className="form-error">{error}</p>}<button className="primary-button" type="submit" disabled={pending}>{pending ? 'Signing in...' : 'Sign in'} <Zap size={16} /></button><p className="switch-copy">New to NOC Automation? <Link to="/register">Create an account</Link></p></form></AuthLayout>
}
function Register() {
  const { register } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const update = key => event => setForm({ ...form, [key]: event.target.value })
  const submit = async event => { event.preventDefault(); setError(''); setPending(true); try { await register(form.name || 'Operations User', form.email, form.password); navigate('/dashboard') } catch (requestError) { setError(requestError.message) } finally { setPending(false) } }
  return <AuthLayout eyebrow="Create workspace access" title={<>One view for<br /><span>every system.</span></>} text="Set up your NOC Automation profile and bring monitoring, response, and reporting into one focused workspace."><form className="auth-form" onSubmit={submit}><Field label="Full name" value={form.name} onChange={update('name')} placeholder="Jordan Lee" required /><Field label="Work email" type="email" value={form.email} onChange={update('email')} placeholder="you@company.com" required /><Field label="Password" type="password" value={form.password} onChange={update('password')} placeholder="Create a password" minLength="8" required />{error && <p className="form-error">{error}</p>}<button className="primary-button" type="submit" disabled={pending}>{pending ? 'Creating account...' : 'Create account'} <UserPlus size={16} /></button><p className="switch-copy">Already have access? <Link to="/login">Sign in</Link></p></form></AuthLayout>
}
function ForgotPassword() {
  const [sent, setSent] = useState(false)
  return <AuthLayout eyebrow="Account recovery" title={<>Back to a<br /><span>clear signal.</span></>} text="Enter your work email and we will send a secure link to reset your password."><form className="auth-form" onSubmit={event => { event.preventDefault(); setSent(true) }}>{sent ? <div className="success-message"><span><Check size={18} /></span><div><strong>Reset link sent</strong><p>Check your inbox for the next step. The link expires in 30 minutes.</p></div></div> : <><Field label="Work email" type="email" placeholder="you@company.com" required /><button className="primary-button" type="submit">Send reset link <LockKeyhole size={16} /></button></>}<p className="switch-copy"><Link to="/login">Return to sign in</Link></p></form></AuthLayout>
}
function Field({ label, ...props }) { return <label className="field">{label}<input {...props} /></label> }
function RoleSelect({ value, onChange }) { return <label className="field">Workspace role<select value={value} onChange={onChange}><option>Admin</option><option>Operator</option><option>Viewer</option></select></label> }

function AppShell() {
  const [open, setOpen] = useState(false); const [darkMode, setDarkMode] = useState(() => localStorage.getItem('noc-automation-theme') === 'dark'); const { user, signOut } = useAuth(); const location = useLocation()
  useEffect(() => { window.scrollTo(0, 0); setOpen(false) }, [location.pathname])
  const toggleTheme = () => { const next = !darkMode; setDarkMode(next); localStorage.setItem('noc-automation-theme', next ? 'dark' : 'light') }
  return <div className={`app-shell ${darkMode ? 'dark-mode' : ''}`}><aside className={`sidebar ${open ? 'is-open' : ''}`}><div className="sidebar-top"><Link to="/dashboard" className="brand brand-light"><span className="brand-mark"><span /></span><span>NOC <span className="brand-accent">Automation</span></span></Link><button className="close-menu" onClick={() => setOpen(false)} aria-label="Close navigation"><X size={20} /></button></div><div className="workspace-switcher"><span className="workspace-icon"><Network size={15} /></span><span><small>WORKSPACE</small><strong>Enterprise Operations</strong></span><ChevronDown size={16} /></div><nav className="sidebar-nav"><span className="nav-label">Monitor</span><NavLink to="/dashboard" className={({ isActive }) => isActive ? 'active' : ''}><LayoutDashboard size={17} />Dashboard</NavLink><NavLink to="/monitoring" className={({ isActive }) => isActive ? 'active' : ''}><Activity size={17} />Monitoring</NavLink><NavLink to="/alerts" className={({ isActive }) => isActive ? 'active' : ''}><Bell size={17} />Alerts<span className="nav-count alert">7</span></NavLink><span className="nav-label">Analyze</span><NavLink to="/reports" className={({ isActive }) => isActive ? 'active' : ''}><Database size={17} />Reports</NavLink><span className="nav-label">System</span><NavLink to="/settings" className={({ isActive }) => isActive ? 'active' : ''}><Settings size={17} />Settings</NavLink></nav><div className="sidebar-bottom"><div className="support-card"><ShieldCheck size={18} /><div><strong>All systems protected</strong><span>Last checked 2 min ago</span></div></div><button className="signout" onClick={signOut}><LogOut size={16} />Sign out</button></div></aside><div className="main-area"><header className="topbar"><button className="mobile-menu" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu size={21} /></button><div className="topbar-search"><Search size={17} /><input placeholder="Search infrastructure..." /></div><div className="topbar-actions"><button className="icon-button" onClick={toggleTheme} aria-label={darkMode ? 'Use light mode' : 'Use dark mode'}>{darkMode ? <Sun size={18} /> : <Moon size={18} />}</button><button className="icon-button" aria-label="Notifications"><Bell size={18} /><span /></button><div className="user-menu"><span className="avatar">{(user?.name || 'OP').slice(0, 2).toUpperCase()}</span><div><strong>{user?.name || 'Operator'}</strong><small>{user?.role || 'Operator'}</small></div><ChevronDown size={15} /></div></div></header><main className="dashboard-main"><Dashboard /></main></div>{open && <button className="mobile-scrim" onClick={() => setOpen(false)} aria-label="Close navigation overlay" />}</div>
}

const metrics = [
  { label: 'CPU usage', value: '42.8%', detail: 'across monitored hosts', icon: Cpu, tone: 'cyan', trend: '-8.4%' },
  { label: 'RAM usage', value: '68.4%', detail: 'of allocated capacity', icon: Database, tone: 'blue', trend: '+2.1%' },
  { label: 'Disk usage', value: '71.2%', detail: 'average utilization', icon: HardDrive, tone: 'amber', trend: '-1.6%' },
  { label: 'Network traffic', value: '1.84 GB/s', detail: 'across monitored links', icon: Network, tone: 'green', trend: '+6.8%' },
  { label: 'Active alerts', value: '7', detail: '3 require attention', icon: Bell, tone: 'amber', trend: '-12%' },
  { label: 'Device count', value: '126', detail: 'networked devices', icon: Network, tone: 'cyan', trend: '+8' },
  { label: 'Server count', value: '48', detail: 'managed servers', icon: Server, tone: 'green', trend: '+2' },
]
function Dashboard() {
  const location = useLocation(); const [dashboardData, setDashboardData] = useState(null); const [refreshing, setRefreshing] = useState(false)
  const refresh = () => { setRefreshing(true); mockApi.getDashboard().then(setDashboardData).finally(() => setRefreshing(false)) }
  useEffect(() => { refresh() }, [])
  if (location.pathname === '/monitoring') return <MonitoringPage />
  if (location.pathname === '/alerts') return <AlertsPage />
  if (location.pathname === '/reports') return <ReportsPage />
  if (location.pathname === '/settings') return <SettingsPage />
  const liveValues = dashboardData ? { 'CPU usage': `${dashboardData.cpu}%`, 'RAM usage': `${dashboardData.ram}%`, 'Disk usage': `${dashboardData.disk}%`, 'Network traffic': dashboardData.traffic, 'Active alerts': dashboardData.alerts, 'Device count': dashboardData.devices, 'Server count': dashboardData.servers } : {}
  return <div className="dashboard"><div className="dashboard-heading"><div><span className="auth-eyebrow">Tuesday, September 16, 2026</span><h1>Good morning, <span>Operations.</span></h1><p>Here is the latest pulse across your enterprise environment.</p></div><button className="outline-button" onClick={refresh} disabled={refreshing}><Activity size={16} />{refreshing ? 'Refreshing...' : 'Live refresh'}</button></div><div className="metric-grid">{metrics.map(metric => <MetricCard key={metric.label} {...metric} value={liveValues[metric.label] || metric.value} />)}</div><div className="dashboard-grid"><ServerStatus /><UsageChart /><Alerts /><MonitoringSummary /><PingStatus /></div><SuccessStories /><TeamSection /><ContactSection /></div>
}
function PageHeader({ eyebrow, title, text, action }) { return <div className="page-heading"><div><span className="auth-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{action && <button className="outline-button">{action}</button>}</div> }
function PingStatus() { const locations = [['Chicago edge', '18 ms', 'green'], ['Frankfurt edge', '92 ms', 'green'], ['Singapore edge', '184 ms', 'amber']]; return <section className="dashboard-card ping-card"><CardHeader eyebrow="Connectivity" title="Ping status" action={{ label: 'View probes', href: '#monitoring' }} /><div className="ping-summary"><strong>99.97%</strong><span>average reachability</span></div><div className="ping-list">{locations.map(([name, latency, tone]) => <div key={name}><span className="server-status-dot" data-tone={tone} /><strong>{name}</strong><span>{latency}</span></div>)}</div></section> }
function MonitoringPage() { const [devices, setDevices] = useState([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState('All'); const [selected, setSelected] = useState(null); useEffect(() => { mockApi.getDevices().then(data => { setDevices(data); setSelected(data[0]) }) }, []); const filtered = devices.filter(device => (status === 'All' || device.status === status) && `${device.name} ${device.id} ${device.type} ${device.location}`.toLowerCase().includes(query.toLowerCase())); return <div className="dashboard"><PageHeader eyebrow="Monitoring" title={<>Know what is<br /><span>happening now.</span></>} text="Live health signals from every monitored server, device, and network path." action="Refresh data" /><div className="metric-grid">{metrics.slice(0, 4).map(metric => <MetricCard key={metric.label} {...metric} />)}</div><div className="monitoring-layout"><section className="dashboard-card monitor-table"><CardHeader eyebrow="Monitored assets" title={`${filtered.length} devices online`} /><div className="monitor-toolbar"><div className="device-search"><Search size={15} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search devices..." /></div><select value={status} onChange={event => setStatus(event.target.value)}><option>All</option><option>Operational</option><option>Degraded</option><option>Warning</option></select></div><div className="table-row table-head"><span>Asset</span><span>Type</span><span>Location</span><span>Health</span></div>{filtered.map(device => <button className={`table-row device-row ${selected?.id === device.id ? 'selected' : ''}`} key={device.id} onClick={() => setSelected(device)}><strong>{device.id}</strong><span>{device.type}</span><span>{device.location}</span><span className={`status-pill ${device.status === 'Operational' ? 'green' : 'amber'}`}>{device.status}</span></button>)}</section><DeviceDetail device={selected} /></div></div> }
function DeviceDetail({ device }) { if (!device) return <section className="dashboard-card device-detail"><span className="auth-eyebrow">Device detail</span><h2>Select a device</h2><p>Choose an asset from the inventory to inspect health and connectivity.</p></section>; return <section className="dashboard-card device-detail"><div className="detail-heading"><div><span className="auth-eyebrow">Device detail</span><h2>{device.name}</h2><p>{device.id} &middot; {device.ip}</p></div><span className={`status-pill ${device.status === 'Operational' ? 'green' : 'amber'}`}>{device.status}</span></div><div className="detail-stats"><span><strong>{device.uptime}</strong><small>Uptime</small></span><span><strong>{device.ping} ms</strong><small>Ping latency</small></span><span><strong>{device.lastCheck}</strong><small>Last check</small></span></div><div className="detail-bars"><UsageBar label="CPU" value={device.cpu} tone="cyan" /><UsageBar label="RAM" value={device.ram} tone="blue" /><UsageBar label="Disk" value={device.disk} tone="amber" /></div><button className="outline-button">Open device history</button></section> }
function UsageBar({ label, value, tone }) { return <div className="usage-bar"><div><span>{label}</span><strong>{value}%</strong></div><i className={tone} style={{ width: `${value}%` }} /></div> }
function AlertsPage() { const [items, setItems] = useState([]); const [severity, setSeverity] = useState('All'); useEffect(() => { mockApi.getAlerts().then(setItems) }, []); const filtered = items.filter(item => severity === 'All' || item.severity === severity); return <div className="dashboard"><PageHeader eyebrow="Alerts" title={<>Resolve issues<br /><span>before impact.</span></>} text="Prioritized incidents and threshold events across the NOC estate." action="Acknowledge all" /><div className="alert-filters"><button className={severity === 'All' ? 'active' : ''} onClick={() => setSeverity('All')}>All <span>{items.length}</span></button>{['Critical', 'Warning', 'Information'].map(level => <button className={severity === level ? 'active' : ''} key={level} onClick={() => setSeverity(level)}>{level} <span>{items.filter(item => item.severity === level).length}</span></button>)}</div><div className="dashboard-grid"><section className="dashboard-card alerts-card"><CardHeader eyebrow="Current queue" title={`${filtered.length} active alerts`} /><div className="alert-list">{filtered.map(item => <div className="alert-row detailed-alert" key={item.id}><span className={`alert-icon ${item.severity.toLowerCase()}`}><AlertTriangle size={15} /></span><span><strong>{item.title}</strong><small>{item.device} &middot; {item.time}</small></span><span className="alert-state">{item.status}</span></div>)}</div></section><section className="dashboard-card alert-health"><CardHeader eyebrow="Response health" title="Alert performance" /><div className="alert-stat"><strong>14 min</strong><span>mean time to acknowledge</span></div><div className="alert-stat"><strong>96.4%</strong><span>alerts resolved within SLA</span></div><div className="summary-note"><Check size={15} /> Response targets are on track</div></section></div><section className="dashboard-card monitor-table"><CardHeader eyebrow="Alert history" title="Recent activity" /><div className="table-row table-head"><span>Incident</span><span>Severity</span><span>Device</span><span>Detail</span></div>{items.map(item => <div className="table-row" key={item.id}><strong>{item.title}</strong><span>{item.severity}</span><span>{item.device}</span><span>{item.detail}</span></div>)}</section></div> }
function ReportsPage() { const [report, setReport] = useState(null); useEffect(() => { mockApi.getReports().then(setReport) }, []); const download = (period, format) => { const blob = new Blob([`NOC Automation ${period} report\nAvailability: ${report?.monthly || 99.98}%\nIncidents resolved: ${report?.incidents || 38}`], { type: format === 'CSV' ? 'text/csv' : 'application/pdf' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `noc-automation-${period.toLowerCase()}-report.${format === 'CSV' ? 'csv' : 'pdf'}`; link.click(); URL.revokeObjectURL(url) }; return <div className="dashboard"><PageHeader eyebrow="Reports" title={<>Operational clarity<br /><span>on demand.</span></>} text="Shareable performance summaries for infrastructure, availability, and response." action="Generate report" /><div className="report-grid"><ReportCard period="Daily" value={report ? '99.98%' : '—'} detail="Availability across the last 24 hours" onDownload={() => download('Daily', 'PDF')} /><ReportCard period="Weekly" value={report ? '99.96%' : '—'} detail="Availability across the last 7 days" onDownload={() => download('Weekly', 'CSV')} /><ReportCard period="Monthly" value={report ? '99.98%' : '—'} detail="Availability across the last 30 days" onDownload={() => download('Monthly', 'PDF')} /></div><section className="dashboard-card report-chart"><CardHeader eyebrow="Monthly trend" title="Service availability" /><div className="report-bars">{[92, 94, 91, 96, 95, 98, 97, 99, 98, 99, 99, 100].map((height, index) => <span key={index} style={{ height: `${height}%` }} />)}</div><div className="chart-axis"><span>Oct</span><span>Dec</span><span>Feb</span><span>Apr</span><span>Jun</span><span>Sep</span></div></section></div> }
function ReportCard({ period, value, detail, onDownload }) { return <article className="report-card"><span className="auth-eyebrow">{period} report</span><strong>{value}</strong><p>{detail}</p><button className="outline-button" onClick={onDownload}>Export report <Database size={14} /></button></article> }
function SettingsPage() { const [settings, setSettings] = useState(null); const [tab, setTab] = useState('profile'); const [saved, setSaved] = useState(false); useEffect(() => { mockApi.getSettings().then(setSettings) }, []); if (!settings) return <div className="dashboard"><PageHeader eyebrow="Settings" title="Loading settings" text="Retrieving workspace configuration." /></div>; return <div className="dashboard"><PageHeader eyebrow="Settings" title={<>Tune the<br /><span>operations center.</span></>} text="Configure monitoring preferences, notification routing, and workspace roles." /><div className="settings-tabs"><button className={tab === 'profile' ? 'active' : ''} onClick={() => setTab('profile')}>User Profile</button><button className={tab === 'notifications' ? 'active' : ''} onClick={() => setTab('notifications')}>Notification Settings</button><button className={tab === 'roles' ? 'active' : ''} onClick={() => setTab('roles')}>Role Management</button></div><section className="dashboard-card settings-card settings-panel">{tab === 'profile' && <><CardHeader eyebrow="Account" title="User profile" /><label className="settings-field">Full name<input defaultValue={settings.profile.name} /></label><label className="settings-field">Work email<input defaultValue={settings.profile.email} type="email" /></label><label className="settings-field">Current role<input defaultValue={settings.profile.role} readOnly /></label></>}{tab === 'notifications' && <><CardHeader eyebrow="Routing" title="Notification settings" /><label className="toggle-row"><span><strong>Critical alerts</strong><small>Notify the on-call operator immediately</small></span><input type="checkbox" defaultChecked={settings.notifications.critical} /></label><label className="toggle-row"><span><strong>Daily digest</strong><small>Send a morning summary to administrators</small></span><input type="checkbox" defaultChecked={settings.notifications.digest} /></label><label className="toggle-row"><span><strong>Maintenance windows</strong><small>Suppress expected changes during windows</small></span><input type="checkbox" defaultChecked={settings.notifications.maintenance} /></label></>}{tab === 'roles' && <><CardHeader eyebrow="Access control" title="Role management" /><div className="role-list">{settings.roles.map((role, index) => <div key={role}><span className={`role-badge role-${index}`}>{role.slice(0, 1)}</span><span><strong>{role}</strong><small>{index === 0 ? 'Full platform administration' : index === 1 ? 'Monitor and respond to incidents' : 'Read-only monitoring access'}</small></span><ChevronDown size={15} /></div>)}</div></>}<button className="primary-button" onClick={() => setSaved(true)}>{saved ? 'Settings saved' : 'Save changes'} <Check size={16} /></button></section></div> }
function MetricCard({ label, value, detail, icon: Icon, tone, trend }) { return <article className="metric-card"><div className={`metric-icon ${tone}`}><Icon size={18} /></div><div className="metric-card-top"><span>{label}</span><span className={`trend ${trend.startsWith('+') ? 'positive' : 'negative'}`}>{trend}</span></div><strong>{value}</strong><small>{detail}</small></article> }
function CardHeader({ eyebrow, title, action }) { return <div className="card-header"><div><span>{eyebrow}</span><h2>{title}</h2></div>{action && <a href={action.href || '#'}>{action.label}</a>}</div> }
function ServerStatus() { const servers = [['PRD-WEB-01', 'Customer portal', 'Operational', 'green'], ['SQL-CORE-02', 'Finance database', 'Operational', 'green'], ['FILE-OPS-04', 'Operations file services', 'Degraded', 'amber'], ['DR-VAULT-01', 'Disaster recovery vault', 'Operational', 'green']]; return <section className="dashboard-card server-card" id="servers"><CardHeader eyebrow="Infrastructure" title="Server status" action={{ label: 'View all 48', href: '#servers' }} /><div className="server-list">{servers.map(([name, type, status, tone]) => <div className="server-row" key={name}><span className="server-status-dot" data-tone={tone} /><span className="server-name"><strong>{name}</strong><small>{type}</small></span><span className={`status-pill ${tone}`}>{status}</span><span className="server-pulse"><i /><i /><i /><i /><i /></span></div>)}</div></section> }
function UsageChart() { const bars = [34, 45, 41, 56, 48, 64, 58, 70, 54, 62, 74, 61, 68, 58, 73, 66, 78, 71, 68, 72, 63, 57, 64, 59]; return <section className="dashboard-card usage-card"><CardHeader eyebrow="Performance" title="Resource usage" action={{ label: 'Last 24 hours', href: '#usage' }} /><div className="chart-legend"><span><i className="legend-cyan" />CPU</span><span><i className="legend-blue" />Memory</span><span className="chart-value">68.4% avg.</span></div><div className="bar-chart">{bars.map((height, index) => <div className="bar-group" key={index}><i style={{ height: `${height}%` }} /><i style={{ height: `${Math.max(24, height - 17)}%` }} /></div>)}</div><div className="chart-axis"><span>12 AM</span><span>6 AM</span><span>12 PM</span><span>6 PM</span><span>Now</span></div></section> }
function Alerts() { const alerts = [['SQL replication latency', 'SQL-CORE-02', '12 min ago', 'high'], ['Storage capacity above 70%', 'FILE-OPS-04', '38 min ago', 'medium'], ['TLS certificate expires in 14 days', 'PRD-WEB-01', '2 hrs ago', 'low']]; return <section className="dashboard-card alerts-card" id="alerts"><CardHeader eyebrow="Needs attention" title="Active alerts" action={{ label: 'Open alert center', href: '#alerts' }} /><div className="alert-list">{alerts.map(([title, host, time, level]) => <div className="alert-row" key={title}><span className={`alert-icon ${level}`}><AlertTriangle size={15} /></span><span><strong>{title}</strong><small>{host} &middot; {time}</small></span><ChevronDown size={15} /></div>)}</div></section> }
function MonitoringSummary() { return <section className="dashboard-card summary-card"><CardHeader eyebrow="Coverage" title="Monitoring summary" /><div className="summary-ring"><div><strong>96%</strong><span>monitored</span></div></div><div className="summary-stats"><span><i className="green-dot" />48 servers</span><span><i className="cyan-dot" />32 services</span><span><i className="blue-dot" />86 checks</span></div><div className="summary-note"><Check size={15} /> Monitoring is healthy</div></section> }
function SuccessStories() { return <section className="stories-section" id="infrastructure"><div className="section-intro"><span className="auth-eyebrow">Customer outcomes</span><h2>Infrastructure that<br /><span>earns trust.</span></h2><p>Enterprise teams use NOC Automation to turn operational data into resilient services and confident decisions.</p></div><div className="story-grid"><article><span className="story-number">01</span><strong>42%</strong><h3>faster incident response</h3><p>Meridian Logistics unified network and server monitoring across 18 distribution sites, reducing mean time to resolution.</p><a href="#contact">Read the story <span>&rarr;</span></a></article><article><span className="story-number">02</span><strong>99.98%</strong><h3>critical platform availability</h3><p>HarborPoint Financial automated cloud health checks and recovery workflows across its customer-facing services.</p><a href="#contact">Read the story <span>&rarr;</span></a></article></div></section> }
function TeamSection() { return <section className="team-section" id="team"><div className="section-intro"><span className="auth-eyebrow">Your operations team</span><h2>People who keep<br /><span>systems moving.</span></h2></div><div className="team-list"><div><span className="team-avatar teal">JM</span><span><strong>Jordan Miller</strong><small>Infrastructure Lead</small></span><span className="online"><i />Available</span></div><div><span className="team-avatar blue">SK</span><span><strong>Samira Khan</strong><small>Security Operations</small></span><span className="online"><i />Available</span></div><div><span className="team-avatar amber">DR</span><span><strong>Diego Ruiz</strong><small>Automation Architect</small></span><span className="online away"><i />In a meeting</span></div></div></section> }
function ContactSection() { return <section className="contact-banner" id="contact"><div><span className="auth-eyebrow">Talk to our team</span><h2>Make your next<br /><span>move with confidence.</span></h2><p>Talk to a NOC Automation specialist about network monitoring, cloud operations, security, and your next reliability goal.</p></div><a className="primary-button" href="mailto:operations@nocautomation.com">Contact operations <Zap size={16} /></a></section> }

export default App
